name: CustomScore
main: Joshet18\CustomScoreboard\Loader
description: "a plugin that allows you to display and customize scoreboards to your liking"
version: 1.0.2
api: 5.0.0
author: Joshet18
src-namespace-prefix: Joshet18\CustomScoreboard
softdepend: [RankSystem, LunarRanks, BedrockEconomy, KDR-Pe, PlayedTime]
permissions:
  customscore:
    default: op
    description: "permission to customcarft command"
  customscore.reload:
    default: op
    description: "permission to execute reload command"
commands:
  scoreboard:
    default: true
    permission: customscore
    description: "customscoreboard commands"
